services:
  postgres:
    image: postgres:17
    container_name: morpion-db
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: morpion
      POSTGRES_USER: morpion
      POSTGRES_PASSWORD: morpion
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
